.TH CLOSEST 1
.SH NAME
closest \- focus the closest window in a given direction
.SH SYNOPSIS
.B closest
.RB ( left | right | up | down )
.SH DESCRIPTION
.B closest
focus the closest window in the direction specified as the argument.
The argument must be one of the following
.TP
.B left
Focus the closest window to the left.
.TP
.B right
Focus the closest window to the right.
.TP
.B left
Focus the closest window upwards.
.TP
.B left
Focus the closest window downwards.
.PP
.B closest
gives preference to windows aligned with the focused window,
this is useful for focusing tiled windows.
.B closest
focus only windows visible in the monitor where the currently focused window is in.
.SH ENVIRONMENT
The following environment variables affect the execution of
.B closest
.TP
.B DISPLAY
The display where the window to be focused is.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B >0
Error occurred.
.SH SEE ALSO
.IR wmutils (1)
.SH HISTORY
An
.B closest
utility appeared in wmutils contrib (https://github.com/wmutils/contrib).
